# Generated by Django 6.0.7 on 2026-07-27 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('document_type', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INVOICE', 'Invoice'), ('CONTRACT', 'Contract'), ('EMAIL', 'Email'), ('SUPPORT_TICKET', 'Support Ticket'), ('PURCHASE_ORDER', 'Purchase Order')], default='UNKNOWN', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
