# Generated by Django 6.0.7 on 2026-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('EXTRACTING', 'EXTRACTING'), ('ANALYZING', 'ANALYZING'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='UPLOADED', max_length=30),
        ),
    ]
