# Generated by Django 6.0.7 on 2026-07-29 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
            ],
            options={
                'db_table': 'document_processing_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='doc_log_doc_status_idx'), models.Index(fields=['status', 'started_at'], name='doc_log_status_time_idx')],
            },
        ),
    ]
